jgeorge37/acmwosu-db

- acmw-db-app/pages/signin.js
so like no more inheritance and classes. we're just using hooks now
> so many HOOKS we be fishing

- acmw-db-app/components/AddCompanyForm.jsx
- acmw-db-app/components/AddContactForm.jsx
- acmw-db-app/components/CompanyForm.jsx
- acmw-db-app/components/FormComponents/CompanySearchInput.jsx
- acmw-db-app/components/FormComponents/SelectInput.jsx
- acmw-db-app/pages/companycontacts.js
To test go to:
http://localhost:3000/companycontacts
> Added UI for adding a company/contact

- acmw-db-app/pages/forgotPassword.js
> ADA-5 - forgot password view

- acmw-db-app/pages/signin.js
Should check email and password are nonempty and that email is a valid OSU email.
To test:
1. comment out the SSL line in the `postgres` file
2. run `npm run dev`
3. go to `http://localhost:3000/signin`
Email regex should match `lowercasename.number@osu.edu` and `lowercasename.number@buckeyemail.osu.edu`
Edit: https://regexr.com/ to test regex faster
> ADA-60: signin logic

- acmw-db-app/pages/api/student/[pid].js
To test:
0. Get/set-up a local DB instance (if done once before you're good)
1. Add some students to the student table i.e. INSERT INTO student (fname, lname, name_dot_num) VALUES ('brutus', 'buckeye', 'buckeye.1');
2. npm run dev of course
3. Hit http://localhost:3000/api/student/search?[YOUR QUERY HERE] with various queries that must have at least one of fname, lname, or name_dot_num. Example: http://localhost:3000/api/student/search?name_dot_num=george. 
The code will find a substring-based match so if "eorg" is given for last name, my last name (george) would be a match.
When multiple criteria are given, only students who have a substring match in all of the given categories will be returned.
> ADA-45 Create API endpoint to search students

- acmw-db-app/components/NavBar.jsx
- acmw-db-app/pages/attendance.js
- acmw-db-app/pages/companycontacts.js
- acmw-db-app/pages/scholarshipprogress.js
- acmw-db-app/pages/signin.js
- acmw-db-app/styles/Database.module.css
- acmw-db-app/styles/components/NavBar.module.css
A purpur navigation bar (I wasn't sure what color to use). Anyways to test:
1. Run `npm run dev`
2. Go to `http://localhost:3000/companycontacts`
Should be able to navigate to attendance form, scholarship progress, and logout to the sign in page.
> Navigation bar

- acmw-db-app/pages/api/meeting/[pid].js
- acmw-db-app/pages/api/utility.js
To test:
1. Add some students and accounts that are appropriately associated via the student_id column in account to your local db
2. Add some AU20 and SP21 meetings to your meeting table
3. Add some entries to the meeting_student table with the meeting_id and student_id being unique pairs and corresponding to the ids from the students and meetings you made in previous steps
4. npm run dev
5. Go to http://localhost:3000/api/meeting/student-attendance?id=SOME ID
6. You should get the number of meetings the student went to grouped by semester
7. Go to http://localhost:3000/api/meeting/account-attendance?email=SOME EMAIL
8. Should get same result format as step 6 perhaps with different numbers if the email you gave is associated with a different student than the one you used before.
> Ada 73 student attendance

- acmw-db-app/components/FormComponents/TextField.jsx
- acmw-db-app/components/GHCVolunteerForm.jsx
- acmw-db-app/pages/execdashboard.js
- acmw-db-app/styles/components/CompanyForm.module.css
- acmw-db-app/styles/components/FormComponents.module.css
- Adding a form to add volunteer hours for GHC attendees
To Test:
1. `npm run dev`
2. Go to localhost:3000/execdashboard
3. Click on the "Update GHC Volunteer Hours" button
> - ADA-63, adding an exec board page/dashboard

- acmw-db-app/components/AttendanceForm.jsx
- acmw-db-app/styles/components/AttendanceForm.module.css
I think I got it! Replicated it after ADA 60, sign in logic. I didn't use Sara's TextField or SubmitButton Form Components so I don't know if we need those anymore (unless they are implemented somewhere else?)
To test:
1.) run npm dev
2.) open localhost:3000/attendance
3.) type in the text boxes
> ADA-59-attendance-form-validation

- acmw-db-app/components/FormComponents/StudentSearch.jsx
- acmw-db-app/pages/companycontacts.js
- acmw-db-app/pages/execdashboard.js
To test:
1. Add some students to the student table
2. npm run dev
3. Go to http://localhost:3000/execdashboard? and search for student with first name, last name, or last name.#
Note: I just stuck it on the execdashboard page for testing purposes as there wasn't a place that needed this component as of right now.
> ADA-29 UI Student Search Component

- acmw-db-app/components/FormComponents/TimeSelectionForm.jsx
- acmw-db-app/pages/execdashboard.js
- acmw-db-app/styles/components/FormComponents.module.css
To test:
1. npm run dev
2. Go to http://localhost:3000/execdashboard? and enter hours, minutes, time of day. If the time is valid, then it will display below.
Note: I just stuck it on the execdashboard page for testing purposes as there wasn't a place that needed this component as of right now.
> ADA-90 Time selection component

- README.md
- acmw-db-app/components/FormComponents/TimeSelectionForm.jsx
- acmw-db-app/pages/execdashboard.js
- acmw-db-app/styles/components/FormComponents.module.css
- migrations/SQL/0009_spon-packet-col.sql
- migrations/SQL/0010_meeting-code-exp.sql
- migrations/SQL/0011_ghc-table.sql
Adding GHC table, adding meeting code expiration time column, adding sponsorship packet sent date column (which is for a ticket I had in progress but moved to the backlog since it is not urgent but I already ran the migration on my local and I didn't want to change the versioning and it's just one harmless row)
> Ada 88 ada 93

- acmw-db-app/pages/companycontacts.js
Deploy failed due to double import
> ADA-69 Fix double import

- acmw-db-app/components/FormComponents/DateSelectionForm.jsx
- acmw-db-app/pages/execdashboard.js
To test:
1. npm run dev
2. Go to http://localhost:3000/execdashboard and set a date. If a date was properly set, the chosen date will display below.
> ADA-89 Date Component

- acmw-db-app/pages/api/mailer/[pid].js
- acmw-db-app/pages/reset.js
Minor changes, please review for code quality
> ADA-69 Fix typo in email, add link to sign-in after pw change

- acmw-db-app/components/FormComponents/StudentSearch.jsx
> Ada 53 and ADA 87

- acmw-db-app/pages/_app.js
- acmw-db-app/pages/index.js
This just changes the icon that appears in the browser tab from a triangle to our logo
> Ada 68 and dev - weird branch bc conflicts

- acmw-db-app/components/ScholarshipReqForm.jsx
- acmw-db-app/pages/execdashboard.js
- acmw-db-app/styles/components/CompanyForm.module.css
To test:
1. npm run dev
2. Make sure your local database is running (comment out line in pg-query.js)
3. Go to http://localhost:3000/execdashboard and click on "Add Scholarship Req" button. Look at console message after hitting "Apply"
> ADA-65 Adding GHC scholarship req form

- acmw-db-app/pages/_app.js
- acmw-db-app/pages/index.js
you just gotta go to the dev environment and go to a few pages and check that the icon in the tab is our pruple logo. it might start as the black triangle for a tiny bit since i think the browser tries to remember the icons but it should end up as the logo
> ADA-68 Change icon in tab thing

- acmw-db-app/pages/index.js
- acmw-db-app/styles/Home.module.css
The options on here would change depending on if a user is signed in/what type of user they are. Like the logout wouldn't appear unless a user was signed in already, which I will address in the permissions ticket I have next. 
I made the GHC and exec sign in two different options even though they go to the same page because I thought it would be less confusing for the typical user
Remember this PR is just for code review not testing :)
> Ada 99 home

- migrations/SQL/0012_add-student-constraint.sql
Added a unique constraint on name_dot_num in student table. Tested locally by doing `npm run migrate` and tried to insert the same name_dot_num which correctly resulted in an error.
> Add student unique key constraint

- acmw-db-app/pages/api/ghc/[pid].js
- acmw-db-app/pages/scholarshipprogress.js
I just commented out the previous display bc it seemed like we were tracking which scholarships ppl applied to, but the database just stores a boolean. Not sure if we still want to track what people applied to.
> ADA-58 external scholarship check

- acmw-db-app/pages/api/meeting/[pid].js
To test:
- Use postman/insomnia and do a POST to http://localhost:3000/api/meeting/create
- Provide the meeting_name, meeting_date, semester, and (optional) a company_name already in your local company table
- If successful, a 5 digit code will be returned as part of the data and tables should be updated accordingly
> ADA 84 Meeting Creation

- acmw-db-app/pages/_app.js
- acmw-db-app/pages/index.js
- acmw-db-app/pages/signin.js
i think i fixed the heroku page name issue. just review for code qual
also made the home page links change a bit depending on sign in status
> Ada 42 ada 78 permissions sign out

- acmw-db-app/components/AddAccountForm.jsx
- acmw-db-app/components/FormComponents/SelectInput.jsx
- acmw-db-app/components/FormComponents/StudentSearch.jsx
merged selectinput from dev into this branch
lots of caching to prevent synthetic event error
list no longer uses object values
> reworked w/values

- acmw-db-app/pages/api/meeting/[pid].js
To test:
Use postman/insomnia and do a POST to http://dev-ada.herokuapp.com/api/meeting/create
Provide the meeting_name, meeting_date, semester, and (optional) a company_name already in your local company table
If successful, a 5 digit code will be returned as part of the data and tables should be updated accordingly
> ADA-84 off master branch

- acmw-db-app/components/AttendanceForm.jsx
- acmw-db-app/components/FormComponents/CompanySearchInput.jsx
- acmw-db-app/components/FormComponents/StudentSearch.jsx
- acmw-db-app/components/SelectMeeting.jsx
- acmw-db-app/pages/execdashboard.js
- acmw-db-app/pages/forgotPassword.js
- acmw-db-app/pages/reset.js
- acmw-db-app/pages/scholarshipprogress.js
> Ada 124 cleanup async

- acmw-db-app/styles/Database.module.css
- acmw-db-app/styles/SignIn.module.css
- acmw-db-app/styles/components/ScholarshipProgressBar.module.css
- acmw-db-app/styles/globals.css
see Jira for what this is accomplishing
> Ada 121 113 display fixes

- acmw-db-app/styles/components/ScholarshipProgressBar.module.css
> fix scroll right issue

- migrations/SQL/0014_add-news-col.sql
> Ada 128 newsletter migration

- acmw-db-app/components/AddAccountForm.jsx
- acmw-db-app/pages/api/account/[pid].js
Dev PR for code quality
- Use a randomized password instead of making account creator know the account owner's first password (account owner must use password reset to reset/know their password; otherwise no humans should know it ever)
- Store the selected account type in the database
> Ada 122 127 account type and password

- acmw-db-app/components/AddAccountForm.jsx
- acmw-db-app/pages/api/account/[pid].js
Test in the dev environment - sign in and go to the exec dashboard. Choose the create account option. Make a new dummy account (don't search for existing student); see that you cannot provide a password. 
Now use pgadmin or the heroku CLI with credentials from [here](https://data.heroku.com/datastores/1eca8280-1bfa-4ec8-a382-341bb8b70672#administration) to see that there is in fact a password for this new account (and no one knows what it is).
> ADA-122 ADA-127 Make account creation use random pw and account type

- acmw-db-app/pages/companycontacts.js
- acmw-db-app/styles/components/Form.module.css
Dev PR for code quality - only allow one form in company contacts to be open at once
> Ada 119 exec UI

- acmw-db-app/components/NavBar.jsx
- acmw-db-app/styles/components/NavBar.module.css
- acmw-db-app/styles/globals.css
god bless the cherry pick i really screwed up my branch lol but i think i fixed it
anyway
go to dev and make the screen nice and wide. Then make it narrower, and see that the menu does not wrap when the options get close to the button in the corner. It should collapse and there should be a three line button in the left corner that you can click on to see the menu, then you should be able to click the X button to close. The end
> Ada 114 mobile navbar (#116)

- acmw-db-app/components/AddCompanyForm.jsx
- acmw-db-app/pages/api/company/[pid].js
- acmw-db-app/pages/api/utility.js
- acmw-db-app/pages/scholarshipprogress.js
Dev PR for code quality - making the create company form functional (not creating contact yet though)
> Ada 95 create company

- README.md
- acmw-db-app/components/GHCVolunteerForm.jsx
- acmw-db-app/package.json
- acmw-db-app/pages/api/utility.js
- acmw-db-app/test/pages/api/utility.test.js
- babel.config.cjs
- package-lock.json
- package.json
Dev PR for code quality - this adds unit tests for regex functions. 4 of the tests currently fail, but are commented out, since I made a test block that checks validateLetters for the use of truly wanting to check for only letters, and another block that checks validateLetters for the use of checking names, which can contain spaces, hyphens, accents, and apostrophes, since validateLetters is currently being used to check names. 
There will be a new or updated regex for names next sprint, so those failing cases will be used to test that.
> Ada 137 unit tests

- acmw-db-app/pages/api/meeting/[pid].js
> ADA-135 API endpoint to delete a meeting

- acmw-db-app/components/ManageAccounts.jsx
- acmw-db-app/pages/api/account/[pid].js
- acmw-db-app/pages/execdashboard.js
- acmw-db-app/styles/Database.module.css
- acmw-db-app/styles/components/ManageAccounts.module.css
dev PR for code quality
- API endpoint for listing account info using limit and offset for pagination
- AccountManagement component to view list of accounts 
- Made execdashboard side menu narrower
> Ada 118 account list

- acmw-db-app/pages/api/account/[pid].js
- acmw-db-app/pages/api/mailer/[pid].js
…te 1 hour
just changing 48 hours to one hour for the window for resetting a password to make it more secure
> Ada 139 reset expi

- acmw-db-app/components/AttendanceForm.jsx
- acmw-db-app/pages/api/attendance/[pid].js
right now, according to [the ticket](https://acmwosu.atlassian.net/browse/ADA-26), it is to be assumed the meeting id exists/is correct
> ADA 26 - attendance record business logic for student

- acmw-db-app/components/AttendanceForm.jsx
- acmw-db-app/pages/api/attendance/[pid].js
master pr - i just merged in the commit from the original ADA-26 branch to dev, hope that works
> Ada 26 master/dev

- acmw-db-app/components/AddAccountForm.jsx
- acmw-db-app/pages/api/account/[pid].js
> Ada 120 account exists

- acmw-db-app/components/ScholarshipReqForm.jsx
Didn't import `useEffect` previously and broke everything lol
> import useEffect

- acmw-db-app/components/AddAccountForm.jsx
- acmw-db-app/pages/api/account/[pid].js
To test:
1. Use postman to check GET http://dev-ada.herokuapp.com/api/account/exists?email= with an email and it should return either the row information with the email or zero rows if it does not exist
2. Go to Exec Dashboard page and then create account tab. Using student search, try adding an account that has already been created and an error message will pop up at the bottom
> ADA 120 notify user if account exists

- acmw-db-app/components/ScholarshipReqForm.jsx
- acmw-db-app/pages/api/ghc/[pid].js
trying one more time i had some typos I'm a disaster literally typed pq instead of pg
> ADA-97 bug fixes :(

- acmw-db-app/components/AttendanceForm.jsx
- acmw-db-app/pages/api/attendance/[pid].js
business logic for a member recording attendance
testing backend:
in postman: 
- run the app `npm run dev`
- create a meeting in the database that has an event code, since this code assumes that exists 
- now go to postman and hit the endpoint "http://localhost:3000/api/attendance/record"
- no need to create a new student if the one you are testing doesn't exist, this covers that
- body should be of the form: `{"event_code": "", 
"f_name": "",
"l_name_dot_num": "",
"year_level": ""}`
- send
**testing both fe & be:**
in web dev:
- create a meeting in the database that has an event code, since this code assumes that exists 
- go to "https://dev-ada.herokuapp.com/attendance"
- fill out the form with the code created and submit
- check database to see if successful created new student if …
> Ada 26 master

- acmw-db-app/components/AddAccountForm.jsx
no caps conventions bc those arent real
try catch to silence student dup error
> ADA-126 fix bug

- acmw-db-app/components/AddAccountForm.jsx
This is the same as ADA-126 but without all the stuff I accidentally merged from DEV.
To test:
1. Go to exec dashboard add account
2. Do not use student search and add a student that's already in the database (make sure you pick a student whose last name dot dot number is all lowercase. I'm not sure why some are not?)
3. See that it doesn't make another student and there's no error message in console about duplicate student
> Ada 126 unmerged dev

- acmw-db-app/components/ScholarshipReqForm.jsx
- acmw-db-app/pages/api/ghc/[pid].js
- migrations/SQL/0016_add-req-descript-col.sql
To test:
Go to eboard dash to the input scholarship completion tab
Either enter for milly mason.420 or li.10011 since those are the only two people in the ghc table rn or make more students in the ghc table
If you did external scholarship, should be Ext=whatever you wrote for description. ditto for alternative except prefix is Alt=
> Ada 97 to master

- acmw-db-app/pages/api/account/[pid].js
> Hotfix: change token_expire_time to reset_expire_time in account API

- components/NavBar.jsx
Dev PR for code quality - when testing in dev there was a log out issue so I fixed that
> ADA-140 fix log out bug

- components/NavBar.jsx
- pages/_app.js
- pages/api/auth/[pid].js
- pages/signin.js
code qual - fix the "empty" logout button angela found in my master PR
> Ada 140 auth

- pages/execdashboard.js
> Adding a delete meeting button

- components/AddMeetingForm.jsx
- components/AttendanceForm.jsx
- components/FormComponents/SelectInput.jsx
- components/FormComponents/TimeSelectionForm.jsx
- pages/_app.js
- pages/api/attendance/[pid].js
- pages/api/auth/[pid].js
- pages/api/meeting/[pid].js
- pages/execdashboard.js
- styles/Database.module.css
- styles/SignIn.module.css
dev PR for code quality, see ticket descriptions for what this is accomplishing
> Ada 125 132 67 attendance

- pages/execdashboard.js
To test in dev:
- Go to exec dashboard => meetings
- Select a meeting to delete
- Hit yes
- Meeting should be deleted, page should refresh, and attendance should not show
> Ada 136 delete meeting

- components/FormComponents/StudentSearch.jsx
- components/ScholarshipReqForm.jsx
- pages/api/student/[pid].js
code quality pr
basically just modified student search to have a ghcFlag that can be set to true since otherwise it would have been repeated code (default false)
> ADA-147 GHC Search

- pages/api/account/[pid].js
Get the cookie auth token as stated in the readme
go to postman and do a POST on https://dev-ada.herokuapp.com/api/account/delete
where the body is JSON
`
{
"email":"laugh.420@osu.edu"
}
`
but with different emails
> Ada 115 fr

- components/FormComponents/StudentSearch.jsx
- components/GHCVolunteerForm.jsx
- components/ScholarshipReqForm.jsx
- pages/api/ghc/[pid].js
- pages/api/student/[pid].js
> Ada 98 ghc backend

- components/AddMeetingForm.jsx
- pages/api/meeting/[pid].js
> ADA-152 Adding ability to select multiple companies for a meeting

- pages/api/ghc/[pid].js
To test:
**Non-Exec User**
1. Change your is_exec account type to be false, then log in. Using postman, do GET http://dev-ada.herokuapp.com/api/ghc/volunteer-hours with email = [your osu edu email]. Make sure to get your bearer token by doing Inspect->Application->Cookies.
2. If you have information in the ghc table, it should display volunteer_hours, volunteer_sources, and totalHours.
3. If you do not have information, you should add some and verify the information. Note that volunteer_hours and volunteer_sources are stored as arrays.
4. Try any other email address from the database. You should get a "Forbidden" message.
**Exec User**
1. Change your is_exec account type back to true, then log in. Same deal--use postman and use your email to check endpoint. Make sure to update your bearer …
> Ada 10 master
